In [1]:
import pandas as pd
import numpy as np

In [9]:

df = pd.read_csv("superstore_excel-selected-columns.csv")
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders
...,...,...,...,...,...,...,...,...,...,...
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [10]:
df.isnull()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False

In [12]:
df.shape

(5000, 10)

In [13]:
df.dtypes

Order ID         object
Order Date       object
Ship Date        object
Ship Mode        object
Customer ID      object
Customer Name    object
Segment          object
Region           object
Category         object
Sub-Category     object
dtype: object

In [14]:
df.size

50000

In [17]:
df.tail()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [18]:
df.describe()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,5000,728,30,4,3853,4833,3,4,3,14
top,CA-198797,2023-10-15,2025-04-27,Second Class,CUST-2883,Michael Smith,Corporate,South,Furniture,Chairs
freq,1,17,198,1305,5,4,1686,1287,1670,447

In [20]:
a = df[df['Category'] == 'Technology']
a

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
20,CA-431867,2023-09-02,2025-05-07,First Class,CUST-3050,Katherine Rodriguez,Corporate,Central,Technology,Copiers
22,CA-129071,2024-06-15,2025-04-23,Same Day,CUST-9684,Ashley James DDS,Home Office,East,Technology,Accessories
24,CA-758620,2024-07-10,2025-04-25,Standard Class,CUST-7646,Ashley Wilkerson,Consumer,Central,Technology,Accessories
28,CA-930209,2024-11-13,2025-04-15,Same Day,CUST-2863,Mr. Brad Price,Corporate,East,Technology,Copiers
...,...,...,...,...,...,...,...,...,...,...
4990,CA-900960,2025-02-04,2025-05-05,Second Class,CUST-6952,Trevor Mills,Home Office,West,Technology,Accessories
4991,CA-544225,2023-06-20,2025-05-03,First Class,CUST-1952,April Wright,Consumer,Central,Technology,Machines
4993,CA-743555,2023-11-11,2025-04-26,Second Class,CUST-3878,Mary Ramirez,Consumer,West,Technology,Copiers
4994,CA-450931,2024-12-23,2025-04-25,Second Class,CUST-5025,Lisa Moore,Corporate,South,Technology,Accessories
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories

In [22]:
c = df.sort_values(by= "Segment", ascending=False)
c

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
2446,CA-807622,2023-05-15,2025-04-23,Same Day,CUST-7753,Margaret Brown,Home Office,East,Office Supplies,Art
2436,CA-282706,2024-02-08,2025-04-19,Standard Class,CUST-4066,Lisa Anderson,Home Office,Central,Technology,Accessories
2437,CA-322029,2025-01-11,2025-04-17,Second Class,CUST-7665,Robert Richmond,Home Office,Central,Office Supplies,Labels
2438,CA-849586,2024-12-15,2025-04-24,Same Day,CUST-6465,Lawrence Armstrong,Home Office,South,Office Supplies,Binders
...,...,...,...,...,...,...,...,...,...,...
2149,CA-649829,2023-10-15,2025-04-13,Second Class,CUST-3681,Andrea Rivera,Consumer,West,Technology,Machines
455,CA-926302,2025-02-10,2025-05-05,Second Class,CUST-4120,Clinton Rangel,Consumer,West,Furniture,Bookcases
3603,CA-431678,2023-10-03,2025-04-19,Same Day,CUST-7989,Christine Richardson,Consumer,South,Furniture,Furnishings
3602,CA-518533,2023-08-10,2025-04-20,Standard Class,CUST-7597,Donald Reyes,Consumer,East,Furniture,Chairs
992,CA-502874,2024-02-01,2025-04-29,Standard Class,CUST-8782,Randy Little,Consumer,South,Office Supplies,Paper

In [23]:
d = df.groupby("Category")
print(d)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001A947B4D340>

In [24]:
df.info

<bound method DataFrame.info of        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0     CA-198797  2024-10-06  2025-05-01    Second Class   CUST-4170
1     CA-233440  2023-06-12  2025-05-05     First Class   CUST-1196
2     CA-691533  2024-04-18  2025-04-24  Standard Class   CUST-2985
3     CA-277218  2023-11-02  2025-05-07     First Class   CUST-2412
4     CA-311967  2023-07-15  2025-04-14     First Class   CUST-3728
...         ...         ...         ...             ...         ...
4995  CA-780853  2025-03-04  2025-04-13    Second Class   CUST-8307
4996  CA-489090  2023-06-20  2025-04-28        Same Day   CUST-1311
4997  CA-203624  2024-03-11  2025-04-23  Standard Class   CUST-6014
4998  CA-562734  2024-11-04  2025-04-20        Same Day   CUST-1274
4999  CA-852804  2024-03-22  2025-04-24     First Class   CUST-6238

       Customer Name      Segment   Region         Category Sub-Category
0      Ruben Ramirez  Home Office    South       Technology      Copiers
1       Jesse Ortega  Home Office  Central        Furniture  Furnishings
2     Kathryn Castro    Corporate     East        Furniture       Chairs
3      Sharon Taylor     Consumer    South  Office Supplies       Labels
4      David Murillo    Corporate    South  Office Supplies      Binders
...              ...          ...      ...              ...          ...
4995      Adam Scott  Home Office     West  Office Supplies          Art
4996  Kathryn Miller  Home Office    South        Furniture       Chairs
4997  Tiffany Moreno    Corporate     East       Technology  Accessories
4998  Yolanda Conner    Corporate     West        Furniture       Chairs
4999   Michael Giles  Home Office     East        Furniture       Chairs

[5000 rows x 10 columns]>